### PR TITLE
Verify deployments based on container image digests, not tagging

### PR DESCRIPTION
**Pull request by alexwlchan**
For https://github.com/wellcomecollection/platform/issues/5597. This is a new approach to verifying whether a release is successfully deployed, using the image digests rather than tags managed by weco-deploy.

1. This patch introduces the notion of a "task spec", which is meant to be an unambiguous statement of what images we expect to be running in a particular service at a given time:

    ```json
    {
      "task_definition": "arn:aws:ecs:eu-west-1:756629837203:task-definition/matcher:4",
      "images": {
        "app": {
          "uri": "ecr.public.123/matcher:env.prod",
          "digest": "sha256:301faf69ff1b1a06166b550ac225a7d7b631e97e83ac9d476bf4e31f8911c576"
        },
        "logging": {
          "uri": "ecr.public.123/logging:env.prod",
          "digest": "sha256:c1bf75cfe97e8765cd838d1579c54a9ca7e460846cfabbc832194938c7aa130b"
        }
      }
    }
    ```

    In particular, because we have floating tags in our task definitions, these image digests may change – we get these digests by asking _"what is the digest of the image currently specified by this tag?"_.

    This is defined by `TaskSpec` in the `models.py` file.

2. When we call the new `has_up_to_date_tasks()` method, we work out an equivalent `images` object for every current task, e.g. a task might have:

    ```json
    {
      "app": {
        "uri": "ecr.public.123/matcher:env.prod",
        "digest": "sha256:26353e694b8d7b150c6f1b094f5e38b7d83b0f7e1757377465976710b1bbe840"
      },
      "logging": {
        "uri": "ecr.public.123/logging:env.prod",
        "digest": "<none>"
      }
    }
    ```

    Here the `app` container is running an old Docker image, and the `logging` container hasn't pulled an image yet, so we don't have a digest.

3. Compare the expected value and the actual value. If they're the same, this task has been successfully deployed. If they're different, we're still waiting for the deployment to complete.

## Benefits of this approach

* We ditch any awareness of 'releases' when checking if images are deployed correctly, which I think is behind the recent logic problems – we'll check the complete set of services specified by this project are up-to-date, with no awareness of what services might have been updated recently.

   Long-term I want us to entirely get away from 'releases' and 'deployments'; this is just one step in that direction.

* We no longer have to set or manage the `deployment:label` tag. Success is determined by running the correct images, not by a separately-managed value.

* Because it just uses the image tags, it's not tied to ECS. In particular, if we _were_ planning to deploy containers into some non-ECS environment, we could reuse a lot of code if we can extract image URIs and currently-running digests. 👀 

## Testing

Doing automated testing of weco-deploy has been a PITA in the past and I haven't really addressed that here. I have been deploying the staging catalogue API back and forth between `latest` and `env.prod` to see what happens; it does seem to place new containers and wait for them to be correct.

This is the output while it's waiting:

```
Task bafda7ab8e30412585a413cd3dfc806b in stage-search-api has the wrong containers:
- app: wrong image digest
    expected: sha256:0438d140618343b26e543015c0afb83fa9b69d185c51e9bed7d392d0f25b29f8
    actual:   sha256:26353e694b8d7b150c6f1b094f5e38b7d83b0f7e1757377465976710b1bbe840

Task c57dba43ccf94f9ca5429e69092cf680 in stage-search-api has the wrong containers:
- app: wrong image digest
    expected: sha256:0438d140618343b26e543015c0afb83fa9b69d185c51e9bed7d392d0f25b29f8
    actual:   sha256:26353e694b8d7b150c6f1b094f5e38b7d83b0f7e1757377465976710b1bbe840
```

### CODE REVIEW

**Review by jamieparkinson — COMMENTED** [review]
Main thought is that the digests are not very user-friendly - how do I easily find which code is running given the log example you've shown?

**Comment by alexwlchan** [comment]
Agree the image digests aren't very readable, but they are how the comparison works, so I want to keep them _somewhere_.

So I think every image digest will be tied to (at least) one ref tag, so how about adding the refs, something like:

```
    expected: sha256:0438d140618343b26e543015c0afb83fa9b69d185c51e9bed7d392d0f25b29f8
              ref.58ddae35c9e7867acd3a2df137ece9984d24f7de
    actual:   sha256:26353e694b8d7b150c6f1b094f5e38b7d83b0f7e1757377465976710b1bbe840
              ref.d2e53d3069a6873d06446547983fae08898066ae
```

Would that be more useful?

**Comment by alexwlchan** [comment]
or even better, use the code we've got elsewhere:

```
    expected: sha256:0438d140618343b26e543015c0afb83fa9b69d185c51e9bed7d392d0f25b29f8
              commit 58ddae3 (Remove the old 'api' repository)
    actual:   sha256:26353e694b8d7b150c6f1b094f5e38b7d83b0f7e1757377465976710b1bbe840
              commit d2e53d3 (Merge pull request #539 from wellcomecollection/bump-tf-ecs-module-version)
```

**Comment by jamieparkinson** [comment]
Think that's good - nit would be to switch the lines so the first thing you read is the commit, followed by the digest for clarity

**Comment by alexwlchan** [comment]
Okay, this is what the latest version looks like:

```
Task e72397d4082e4655b54ef54d558694e1 in stage-concepts-api has the wrong containers:
- app: wrong image digest
    expected: commit a25ebce: Merge pull request #541 from wellcomecollection/remove-old-repo
              sha256:271ef4ad16e6c6a565aa3584afef90ad7f89deaeceaee619d9d6ef3ee6d65506
    actual:   commit e5a461e: Merge pull request #536 from wellcomecollection/bump-scala-libs-to-v32.17.0
              sha256:c1bf75cfe97e8765cd838d1579c54a9ca7e460846cfabbc832194938c7aa130b

Trying again in 10s (waited 3s).

Still waiting for task 642c68622f7b424eb6c0bc7c7130d5d6 in stage-search-api to stop
Still waiting for task e72397d4082e4655b54ef54d558694e1 in stage-search-api to stop
```

It has the new commit explanations as discussed above, but it only gives the detailed report once – so rather than spamming your terminal with output, it just tells you "those tasks I told you about before are still going".

**Comment by alexwlchan** [comment]
And one more change, flipping it around to put the service name first:

```
stage-concepts-api: task a2c51067fcee42a49c8e5e6218e881d4 has the wrong containers:
- app: wrong image digest
    expected: commit e5a461e: Merge pull request #536 from wellcomecollection/bump-scala-libs-to-v32.17.0
              sha256:c1bf75cfe97e8765cd838d1579c54a9ca7e460846cfabbc832194938c7aa130b
    actual:   commit a25ebce: Merge pull request #541 from wellcomecollection/remove-old-repo
              sha256:271ef4ad16e6c6a565aa3584afef90ad7f89deaeceaee619d9d6ef3ee6d65506
Trying again in 10s (waited 3s).
stage-search-api: still waiting for task 1c0c98e84c8b40efa95c003f5c72e22e to stop
stage-search-api: still waiting for task 72d12bca5e6a4b74a6cbd18bbfe5c737 to stop
stage-search-api: still waiting for task e58940e87dee42699da4b82bcb902eb9 to stop
```

**Comment by alexwlchan** [comment]
@jamieparkinson This feels like it's getting a little large and unwieldy; let me know if you'd like to split off some of th pieces into smaller PRs for easier review.

**Review by jamieparkinson — APPROVED** [review]
Think it's fine, it's relatively self-contained

**Pull request merged**
